name: Vercel Preview Deployment

on:
  push:
    branches:
      - meta-pay-dialog-issue
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel Preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "✅ Deployment completed: $url"

      - name: Comment PR with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Vercel Preview Deployment\n\n✅ **Deployed successfully!**\n\n**Preview URL:** ${{ steps.deploy.outputs.url }}\n\n- **Branch:** \`${{ github.ref_name }}\`\n- **Commit:** \`${{ github.sha }}\`\n- **Environment:** Preview`
            })
